// tools/generate_audio.py tarafından üretildi; elle düzenlemeyin.
// Ses: Thorsten-Voice (CC0), Piper nöral TTS ile kaydedildi.
const AUDIO_CLIPS = {
 "der Vater": "audio/der-vater.mp3",
 "die Mutter": "audio/die-mutter.mp3",
 "das Kind": "audio/das-kind.mp3",
 "der Bruder": "audio/der-bruder.mp3",
 "die Schwester": "audio/die-schwester.mp3",
 "das Baby": "audio/das-baby.mp3",
 "der Opa": "audio/der-opa.mp3",
 "die Oma": "audio/die-oma.mp3",
 "die Familie": "audio/die-familie.mp3",
 "das Mädchen": "audio/das-maedchen.mp3",
 "das Buch": "audio/das-buch.mp3",
 "das Heft": "audio/das-heft.mp3",
 "der Kuli": "audio/der-kuli.mp3",
 "der Bleistift": "audio/der-bleistift.mp3",
 "die Tasche": "audio/die-tasche.mp3",
 "die Lehrerin": "audio/die-lehrerin.mp3",
 "der Lehrer": "audio/der-lehrer.mp3",
 "die Schere": "audio/die-schere.mp3",
 "das Lineal": "audio/das-lineal.mp3",
 "der Computer": "audio/der-computer.mp3",
 "die Uhr": "audio/die-uhr.mp3",
 "die Schule": "audio/die-schule.mp3",
 "der Apfel": "audio/der-apfel.mp3",
 "die Banane": "audio/die-banane.mp3",
 "das Brot": "audio/das-brot.mp3",
 "der Käse": "audio/der-kaese.mp3",
 "die Milch": "audio/die-milch.mp3",
 "das Wasser": "audio/das-wasser.mp3",
 "das Ei": "audio/das-ei.mp3",
 "die Tomate": "audio/die-tomate.mp3",
 "der Kuchen": "audio/der-kuchen.mp3",
 "die Pizza": "audio/die-pizza.mp3",
 "das Eis": "audio/das-eis.mp3",
 "der Tee": "audio/der-tee.mp3",
 "der Hund": "audio/der-hund.mp3",
 "die Katze": "audio/die-katze.mp3",
 "das Pferd": "audio/das-pferd.mp3",
 "der Vogel": "audio/der-vogel.mp3",
 "die Maus": "audio/die-maus.mp3",
 "das Schwein": "audio/das-schwein.mp3",
 "der Fisch": "audio/der-fisch.mp3",
 "die Kuh": "audio/die-kuh.mp3",
 "das Kaninchen": "audio/das-kaninchen.mp3",
 "der Löwe": "audio/der-loewe.mp3",
 "die Ente": "audio/die-ente.mp3",
 "das Schaf": "audio/das-schaf.mp3",
 "das Haus": "audio/das-haus.mp3",
 "der Tisch": "audio/der-tisch.mp3",
 "das Bett": "audio/das-bett.mp3",
 "die Tür": "audio/die-tuer.mp3",
 "das Fenster": "audio/das-fenster.mp3",
 "die Lampe": "audio/die-lampe.mp3",
 "der Schlüssel": "audio/der-schluessel.mp3",
 "die Küche": "audio/die-kueche.mp3",
 "das Sofa": "audio/das-sofa.mp3",
 "der Garten": "audio/der-garten.mp3",
 "der Ball": "audio/der-ball.mp3",
 "das Fahrrad": "audio/das-fahrrad.mp3",
 "die Musik": "audio/die-musik.mp3",
 "die Gitarre": "audio/die-gitarre.mp3",
 "das Spiel": "audio/das-spiel.mp3",
 "der Film": "audio/der-film.mp3",
 "die Kamera": "audio/die-kamera.mp3",
 "das Handy": "audio/das-handy.mp3",
 "der Strand": "audio/der-strand.mp3",
 "die Zeitung": "audio/die-zeitung.mp3",
 "Das ist meine Mutter.": "audio/das-ist-meine-mutter.mp3",
 "Ich habe einen Bruder.": "audio/ich-habe-einen-bruder.mp3",
 "Mein Vater heißt Ali.": "audio/mein-vater-heisst-ali.mp3",
 "Meine Oma wohnt in Izmir.": "audio/meine-oma-wohnt-in-izmir.mp3",
 "Ich gehe in die Schule.": "audio/ich-gehe-in-die-schule.mp3",
 "Das Buch ist neu.": "audio/das-buch-ist-neu.mp3",
 "Wir lernen Deutsch.": "audio/wir-lernen-deutsch.mp3",
 "Heute haben wir Mathe.": "audio/heute-haben-wir-mathe.mp3",
 "Ich esse gern Pizza.": "audio/ich-esse-gern-pizza.mp3",
 "Trinkst du Tee?": "audio/trinkst-du-tee.mp3",
 "Der Apfel ist rot.": "audio/der-apfel-ist-rot.mp3",
 "Zum Frühstück esse ich Käse.": "audio/zum-fruehstueck-esse-ich-kaese.mp3",
 "Die Katze schläft.": "audio/die-katze-schlaeft.mp3",
 "Ich habe einen Hund.": "audio/ich-habe-einen-hund.mp3",
 "Der Vogel kann fliegen.": "audio/der-vogel-kann-fliegen.mp3",
 "Hast du ein Haustier?": "audio/hast-du-ein-haustier.mp3",
 "Mein Zimmer ist klein.": "audio/mein-zimmer-ist-klein.mp3",
 "Die Lampe ist auf dem Tisch.": "audio/die-lampe-ist-auf-dem-tisch.mp3",
 "Wir wohnen in einem Haus.": "audio/wir-wohnen-in-einem-haus.mp3",
 "Ich spiele gern Fußball.": "audio/ich-spiele-gern-fussball.mp3",
 "Am Wochenende fahre ich Fahrrad.": "audio/am-wochenende-fahre-ich-fahrrad.mp3",
 "Was machst du heute?": "audio/was-machst-du-heute.mp3",
 "Sie hört Musik.": "audio/sie-hoert-musik.mp3",
 "Ich spiele Fußball.": "audio/ich-spiele-fussball.mp3",
 "Du spielst Fußball.": "audio/du-spielst-fussball.mp3",
 "Er spielt Fußball.": "audio/er-spielt-fussball.mp3",
 "Wir spielen Fußball.": "audio/wir-spielen-fussball.mp3",
 "Ihr spielt Fußball.": "audio/ihr-spielt-fussball.mp3",
 "Sie spielen Fußball.": "audio/sie-spielen-fussball.mp3",
 "Ich lerne Deutsch.": "audio/ich-lerne-deutsch.mp3",
 "Du lernst Deutsch.": "audio/du-lernst-deutsch.mp3",
 "Er lernt Deutsch.": "audio/er-lernt-deutsch.mp3",
 "Ihr lernt Deutsch.": "audio/ihr-lernt-deutsch.mp3",
 "Sie lernen Deutsch.": "audio/sie-lernen-deutsch.mp3",
 "Ich wohne in Berlin.": "audio/ich-wohne-in-berlin.mp3",
 "Du wohnst in Berlin.": "audio/du-wohnst-in-berlin.mp3",
 "Er wohnt in Berlin.": "audio/er-wohnt-in-berlin.mp3",
 "Wir wohnen in Berlin.": "audio/wir-wohnen-in-berlin.mp3",
 "Ihr wohnt in Berlin.": "audio/ihr-wohnt-in-berlin.mp3",
 "Sie wohnen in Berlin.": "audio/sie-wohnen-in-berlin.mp3",
 "Ich komme aus der Türkei.": "audio/ich-komme-aus-der-tuerkei.mp3",
 "Du kommst aus der Türkei.": "audio/du-kommst-aus-der-tuerkei.mp3",
 "Er kommt aus der Türkei.": "audio/er-kommt-aus-der-tuerkei.mp3",
 "Wir kommen aus der Türkei.": "audio/wir-kommen-aus-der-tuerkei.mp3",
 "Ihr kommt aus der Türkei.": "audio/ihr-kommt-aus-der-tuerkei.mp3",
 "Sie kommen aus der Türkei.": "audio/sie-kommen-aus-der-tuerkei.mp3",
 "Ich trinke Wasser.": "audio/ich-trinke-wasser.mp3",
 "Du trinkst Wasser.": "audio/du-trinkst-wasser.mp3",
 "Er trinkt Wasser.": "audio/er-trinkt-wasser.mp3",
 "Wir trinken Wasser.": "audio/wir-trinken-wasser.mp3",
 "Ihr trinkt Wasser.": "audio/ihr-trinkt-wasser.mp3",
 "Sie trinken Wasser.": "audio/sie-trinken-wasser.mp3",
 "Ich heiße Max.": "audio/ich-heisse-max.mp3",
 "Du heißt Max.": "audio/du-heisst-max.mp3",
 "Er heißt Max.": "audio/er-heisst-max.mp3",
 "Wir heißen Max.": "audio/wir-heissen-max.mp3",
 "Ihr heißt Max.": "audio/ihr-heisst-max.mp3",
 "Sie heißen Max.": "audio/sie-heissen-max.mp3",
 "Ich bin müde.": "audio/ich-bin-muede.mp3",
 "Du bist müde.": "audio/du-bist-muede.mp3",
 "Er ist müde.": "audio/er-ist-muede.mp3",
 "Wir sind müde.": "audio/wir-sind-muede.mp3",
 "Ihr seid müde.": "audio/ihr-seid-muede.mp3",
 "Sie sind müde.": "audio/sie-sind-muede.mp3",
 "Ich habe Hunger.": "audio/ich-habe-hunger.mp3",
 "Du hast Hunger.": "audio/du-hast-hunger.mp3",
 "Er hat Hunger.": "audio/er-hat-hunger.mp3",
 "Wir haben Hunger.": "audio/wir-haben-hunger.mp3",
 "Ihr habt Hunger.": "audio/ihr-habt-hunger.mp3",
 "Sie haben Hunger.": "audio/sie-haben-hunger.mp3",
 "Ich esse Brot.": "audio/ich-esse-brot.mp3",
 "Du isst Brot.": "audio/du-isst-brot.mp3",
 "Er isst Brot.": "audio/er-isst-brot.mp3",
 "Wir essen Brot.": "audio/wir-essen-brot.mp3",
 "Ihr esst Brot.": "audio/ihr-esst-brot.mp3",
 "Sie essen Brot.": "audio/sie-essen-brot.mp3",
 "Ich lese ein Buch.": "audio/ich-lese-ein-buch.mp3",
 "Du liest ein Buch.": "audio/du-liest-ein-buch.mp3",
 "Er liest ein Buch.": "audio/er-liest-ein-buch.mp3",
 "Wir lesen ein Buch.": "audio/wir-lesen-ein-buch.mp3",
 "Ihr lest ein Buch.": "audio/ihr-lest-ein-buch.mp3",
 "Sie lesen ein Buch.": "audio/sie-lesen-ein-buch.mp3",
 "Ich spreche Türkisch.": "audio/ich-spreche-tuerkisch.mp3",
 "Du sprichst Türkisch.": "audio/du-sprichst-tuerkisch.mp3",
 "Er spricht Türkisch.": "audio/er-spricht-tuerkisch.mp3",
 "Wir sprechen Türkisch.": "audio/wir-sprechen-tuerkisch.mp3",
 "Ihr sprecht Türkisch.": "audio/ihr-sprecht-tuerkisch.mp3",
 "Sie sprechen Türkisch.": "audio/sie-sprechen-tuerkisch.mp3",
 "Ich fahre Bus.": "audio/ich-fahre-bus.mp3",
 "Du fährst Bus.": "audio/du-faehrst-bus.mp3",
 "Er fährt Bus.": "audio/er-faehrt-bus.mp3",
 "Wir fahren Bus.": "audio/wir-fahren-bus.mp3",
 "Ihr fahrt Bus.": "audio/ihr-fahrt-bus.mp3",
 "Sie fahren Bus.": "audio/sie-fahren-bus.mp3",
 "Ich mache Hausaufgaben.": "audio/ich-mache-hausaufgaben.mp3",
 "Du machst Hausaufgaben.": "audio/du-machst-hausaufgaben.mp3",
 "Er macht Hausaufgaben.": "audio/er-macht-hausaufgaben.mp3",
 "Wir machen Hausaufgaben.": "audio/wir-machen-hausaufgaben.mp3",
 "Ihr macht Hausaufgaben.": "audio/ihr-macht-hausaufgaben.mp3",
 "Sie machen Hausaufgaben.": "audio/sie-machen-hausaufgaben.mp3",
 "Hallo! Ich bin Max.": "audio/hallo-ich-bin-max.mp3",
 "Los geht's!": "audio/los-geht-s.mp3",
 "Lernen macht Spaß!": "audio/lernen-macht-spass.mp3",
 "Der, die oder das?": "audio/der-die-oder-das.mp3",
 "Wie geht's dir?": "audio/wie-geht-s-dir.mp3"
};
